Repository FalkenDev/SparkRentals-Admin-Dashboard, pull requests merged in 2022-11, with the labels that each got.

#6 Setup
  package-lock.json
  package.json
  postcss.config.js
  src/App.js
  src/components/Cities/CityList.jsx
  src/components/Cities/RegisterCityForm.jsx
  src/components/Customers/CustomerList.jsx
  src/components/Dashboard/Databox.jsx
  src/components/Map/Map.jsx
  src/components/Scooters/RegisterScooterForm.jsx
  src/components/Scooters/ScooterList.jsx
  src/components/Searchbar.jsx
  src/components/Sidebar.jsx
  src/components/index.jsx
  src/config/config.json
  src/contexts/ContextProvider.js
  src/index.css
  src/index.js
  src/models/auth.js
  src/models/cities.js
  src/models/scooters.js
  src/models/storage.js
  src/models/users.js
  src/pages/Cities.jsx
  src/pages/Customers.jsx
  src/pages/Dashboard.jsx
  src/pages/Login.jsx
  src/pages/Map.jsx
  src/pages/Scooters.jsx
  src/pages/index.jsx
  tailwind.config.js
Labels: enhancement

#11 New login page working with hardcoded password and username
  src/App.js
  src/assets/LogoBlack.svg
  src/assets/img/BGlogin.png
  src/assets/img/transBGlogin.png
  src/components/Login/LoginForm.jsx
  src/components/index.jsx
  src/data/links.js
  src/pages/Login.jsx
Labels: enhancement

#12 Updated Readme file
  README.md
  public/adminDesign.png
Labels: documentation

#14 Dashboard
  src/assets/icons/Areas.svg
  src/assets/icons/Battery.svg
  src/assets/icons/Mainence.svg
  src/assets/icons/MovingScooter.svg
  src/assets/icons/Scooter.svg
  src/assets/icons/Users.svg
  src/components/Dashboard/DataLists.jsx
  src/components/Dashboard/Databox.jsx
  src/components/Dashboard/StatContainer.jsx
  src/components/Login/LoginForm.jsx
  src/components/Sidebar.jsx
  src/components/index.jsx
  src/data/data.js
  src/data/links.js
  src/index.css
  src/pages/Dashboard.jsx
  tailwind.config.js
Labels: enhancement

#16 *In progress* Map page with new map components
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/Map.css
  src/components/Map/Layers/Layers.js
  src/components/Map/Layers/TileLayer.js
  src/components/Map/Layers/VectorLayer.js
  src/components/Map/Layers/index.js
  src/components/Map/Map.jsx
  src/components/Map/Source/index.js
  src/components/Map/Source/osm.js
  src/components/Map/Source/vector.js
  src/components/Map/Source/xyz.js
  src/components/Searchbar.jsx
  src/config/config.json
  src/contexts/MapContext.js
  src/data/mock/mockdata.js
  src/index.js
  src/models/nominatim.js
  src/pages/Map.jsx
  src/pages/MapOverview.jsx
  src/pages/index.jsx
Labels: enhancement

#18 Fixing EsLint Github actions Bug
  .eslintrc.json
  .github/workflows/eslint.yml
  eslint-results.sarif
  package-lock.json
  package.json
Labels: bug, enhancement

#19 Minor changes
  package-lock.json
  src/App.js
  src/components/Dashboard/DataLists.jsx
  src/components/Dashboard/StatContainer.jsx
  src/config/config.json
  src/data/data.js
  src/data/mock/mockdata.js
Labels: enhancement

#21 Scooter page
  src/components/Scooters/RegisterScooterForm.jsx
  src/components/Scooters/ScooterList.jsx
  src/components/Searchbar.jsx
  src/components/filterbar.jsx
  src/components/index.jsx
  src/data/data.js
  src/data/mock/mockdata.js
  src/models/nominatim.js
  src/pages/MapOverview.jsx
  src/pages/ScooterSelect.jsx
  src/pages/Scooters.jsx
  src/pages/Settings.jsx
  src/pages/index.jsx
Labels: enhancement

#22 Scooter Page
  src/App.js
  src/Map.css
  src/components/Scooters/ScooterList.jsx
  src/components/Scooters/ScooterRadioBtn.jsx
  src/components/Sidebar.jsx
  src/components/index.jsx
  src/data/data.js
  src/data/mock/mockdata.js
  src/index.css
  src/models/auth.js
  src/models/storage.js
  src/pages/MapOverview.jsx
  src/pages/ScooterSelect.jsx
  src/pages/Scooters.jsx
Labels: enhancement
