Repository FalkenDev/SparkRentals-Admin-Dashboard, pull requests merged in 2023-01, with the labels that each got.

#45 Prepaid / Scaling / Settings
  src/App.js
  src/components/AdminPanel.jsx
  src/components/Cities/RegisterCityForm.jsx
  src/components/Customers/CustomerList.jsx
  src/components/Prepaid/PrepaidForm.jsx
  src/components/Prepaid/PrepaidList.jsx
  src/components/Scooters/RegisterScooterForm.jsx
  src/components/Sidebar.jsx
  src/components/index.jsx
  src/data/data.js
  src/models/admin.js
  src/models/auth.js
  src/models/cities.js
  src/models/prepaid.js
  src/pages/Cities.jsx
  src/pages/CitySelect.jsx
  src/pages/Prepaid.jsx
  src/pages/ScooterSelect.jsx
  src/pages/Settings.jsx
Labels: enhancement

#46 Changed name from id to admin_id in delete function
  src/models/admin.js
Labels: bug, Fix

#47 Updated Readme file
  README.md
Labels: documentation

#49 Bug fixes and minor changes
  src/components/Customers/LogForm.jsx
  src/components/Dashboard/DataLists.jsx
  src/components/Dashboard/Databox.jsx
  src/components/Login/LoginForm.jsx
  src/components/Map/Map.jsx
  src/components/Prepaid/PrepaidUses.jsx
  src/components/Scooters/ScooterRadioBtn.jsx
  src/components/Scooters/ScooterSelectList.jsx
  src/index.css
  src/models/prepaid.js
  src/pages/CitySelect.jsx
  src/pages/Dashboard.jsx
  src/pages/Prepaid.jsx
  src/pages/ScooterSelect.jsx
Labels: enhancement, Fix
